### ISSUE TITLE
Boton sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [FlorRoth/StoreProject#41]
## Proceso

1. Ingrese a la app.
2. Me loguee con un usuario.

## Resultado esperado

• Poder activar el modo oscuro sin problemas.

## Resultado actual

• El boton "Drack mode" no genera ninguna accion.

## Captura

![image](https://github.com/FlorRoth/StoreProject/assets/166792979/7bb899bf-2361-4c1e-929a-01fae31841fe)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by gabogarcia1** [comment]
Resuelto en la ultima version, ya estaremos buildeando de vuelta y mandando las nuevas imagenes qrs
